// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_MNnRIzkDlOB3lkGOh3qBkwFKIt2ZBg',
    appId: '1:10390010622:web:df61fe9b43da0ea98f83af',
    messagingSenderId: '10390010622',
    projectId: 'tictactoe-fp-tekber',
    authDomain: 'tictactoe-fp-tekber.firebaseapp.com',
    storageBucket: 'tictactoe-fp-tekber.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwk8fSozBgG6gV13hpc1FdOGe_GWAknFA',
    appId: '1:10390010622:android:334d2d9efc341bed8f83af',
    messagingSenderId: '10390010622',
    projectId: 'tictactoe-fp-tekber',
    storageBucket: 'tictactoe-fp-tekber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaeweY_s3mPag_RV6HHCLdcBzyTKtCkrc',
    appId: '1:10390010622:ios:5a8ee6fa20119d0b8f83af',
    messagingSenderId: '10390010622',
    projectId: 'tictactoe-fp-tekber',
    storageBucket: 'tictactoe-fp-tekber.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeFpTekber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaeweY_s3mPag_RV6HHCLdcBzyTKtCkrc',
    appId: '1:10390010622:ios:5a8ee6fa20119d0b8f83af',
    messagingSenderId: '10390010622',
    projectId: 'tictactoe-fp-tekber',
    storageBucket: 'tictactoe-fp-tekber.firebasestorage.app',
    iosBundleId: 'com.example.tictactoeFpTekber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU_MNnRIzkDlOB3lkGOh3qBkwFKIt2ZBg',
    appId: '1:10390010622:web:e2e16468a229e2ce8f83af',
    messagingSenderId: '10390010622',
    projectId: 'tictactoe-fp-tekber',
    authDomain: 'tictactoe-fp-tekber.firebaseapp.com',
    storageBucket: 'tictactoe-fp-tekber.firebasestorage.app',
  );
}
